### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by tts-nlp** [BridgetteSong/BunchedLPCnet#1]
hi @BridgetteSong ! 
    When I train with this code, the following error occurs
    repeat_fdense2 = torch.repeat_interleave(fdense2, repeat_tensor, dim=1)
RuntimeError: CUDA error: device-side assert triggered
how to fixed this ! thanks!

**Comment by BridgetteSong** [comment]
try this?
`repeat_tensor = torch.ones(fdense2.size(1), dtype=torch.long).cuda() * int(self.frame_size/self.n_samples_per_step)`
`repeat_fdense2 = torch.repeat_interleave(fdense2, repeat_tensor, dim=1)`

**Comment by BridgetteSong** [comment]
run code by this? 
`CUDA_VISIBLE_DEVICES=0 python train_lpcnet.py`

**Comment by tts-nlp** [comment]
the other ERROR 

> RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by BridgetteSong** [comment]
May be the problem of your pytorch version && CUDA version?

**Comment by tts-nlp** [comment]
my version is 
`cuda version :10.1, pytorch==1.3.1`

**Comment by BridgetteSong** [comment]
I share my env:
`pytorch 1.3.1`
`cuda: 10.0`
`tensorflow: 1.14`

**Comment by tts-nlp** [comment]
when make , the following error occur
`src/lpcnet.c:86:17: error: ‘DUAL_FC_1_OUT_SIZE’ undeclared (first use in this function)
     float pdf_1[DUAL_FC_1_OUT_SIZE];
                 ^
src/lpcnet.c:86:17: note: each undeclared identifier is reported only once for each function it appears in
src/lpcnet.c:87:17: error: ‘DUAL_FC_2_OUT_SIZE’ undeclared (first use in this function)
     float pdf_2[DUAL_FC_2_OUT_SIZE];
                 ^
src/lpcnet.c:91:22: error: ‘gru_a_embed_sig_1’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_sig_1, gru_a_input, last_sig[1]);
                      ^
src/lpcnet.c:92:22: error: ‘gru_a_embed_pred_1’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_pred_1, gru_a_input, pred[1]);
                      ^
src/lpcnet.c:93:22: error: ‘gru_a_embed_exc_1’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_exc_1, gru_a_input, last_exc[1]);
                      ^
src/lpcnet.c:95:22: error: ‘gru_a_embed_sig_0’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_sig_0, gru_a_input, last_sig[0]);
                      ^
src/lpcnet.c:96:22: error: ‘gru_a_embed_pred_0’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_pred_0, gru_a_input, pred[0]);
                      ^
src/lpcnet.c:97:22: error: ‘gru_a_embed_exc_0’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_exc_0, gru_a_input, last_exc[0]);
                      ^
src/lpcnet.c:103:21: error: ‘dual_fc_1’ undeclared (first use in this function)
     compute_mdense(&dual_fc_1, pdf_1, net->gru_b_state);
                     ^
src/lpcnet.c:115:24: error: ‘md_embed_sig’ undeclared (first use in this function)
     compute_embedding(&md_embed_sig, exc_embed_out, exc[1]);
                        ^
src/lpcnet.c:116:22: error: ‘dual_fc_2’ undeclared (first use in this function)
     compute_mdense2(&dual_fc_2, pdf_2, net->gru_b_state, exc_embed_out);
                      ^
src/lpcnet.c:87:11: warning: unused variable ‘pdf_2’ [-Wunused-variable]
     float pdf_2[DUAL_FC_2_OUT_SIZE];
           ^
src/lpcnet.c:86:11: warning: unused variable ‘pdf_1’ [-Wunused-variable]
     float pdf_1[DUAL_FC_1_OUT_SIZE];
           ^
Makefile:642: recipe for target 'src/lpcnet.lo' failed
make[1]: *** [src/lpcnet.lo] Error 1
`
how to solve this bugs

**Comment by tts-nlp** [comment]
Is this project complete? I get mistakes as soon as I run. Please give me some guidance. Thank you

**Comment by BridgetteSong** [comment]
1. Because model architecture is updated, many new functions are added to the project.
2. In the original LPCNet, you can download the pretrained model to get `src/nnet_data.c` and `src/nnet_data.h`, and you can compile successfully.
3. So if you have the original LPCNet, just copy the `dump_data` to get features. if you don't have, just keep the `src/nnet_data.c` and `src/nnet_data.h` in the project, and you can also compile successfully.
4. If you delete the `src/nnet_data.c` and `src/nnet_data.h`, you can also dump your trained checkpoint to get `src/nnet_data.c` and `src/nnet_data.h`.

**Comment by tts-nlp** [comment]
hi @BridgetteSong ! when use new model params to compile, the following error occur!
`src/lpcnet.c: In function ‘run_sample_network’:
src/lpcnet.c:86:17: error: ‘DUAL_FC_1_OUT_SIZE’ undeclared (first use in this function)
     float pdf_1[DUAL_FC_1_OUT_SIZE];
                 ^
src/lpcnet.c:86:17: note: each undeclared identifier is reported only once for each function it appears in
src/lpcnet.c:87:17: error: ‘DUAL_FC_2_OUT_SIZE’ undeclared (first use in this function)
     float pdf_2[DUAL_FC_2_OUT_SIZE];
                 ^
src/lpcnet.c:91:22: error: ‘gru_a_embed_sig_1’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_sig_1, gru_a_input, last_sig[1]);
                      ^
src/lpcnet.c:92:22: error: ‘gru_a_embed_pred_1’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_pred_1, gru_a_input, pred[1]);
                      ^
src/lpcnet.c:93:22: error: ‘gru_a_embed_exc_1’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_exc_1, gru_a_input, last_exc[1]);
                      ^
src/lpcnet.c:95:22: error: ‘gru_a_embed_sig_0’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_sig_0, gru_a_input, last_sig[0]);
                      ^
src/lpcnet.c:96:22: error: ‘gru_a_embed_pred_0’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_pred_0, gru_a_input, pred[0]);
                      ^
src/lpcnet.c:97:22: error: ‘gru_a_embed_exc_0’ undeclared (first use in this function)
     accum_embedding(&gru_a_embed_exc_0, gru_a_input, last_exc[0]);
                      ^
src/lpcnet.c:103:21: error: ‘dual_fc_1’ undeclared (first use in this function)
     compute_mdense(&dual_fc_1, pdf_1, net->gru_b_state);
                     ^
src/lpcnet.c:115:24: error: ‘md_embed_sig’ undeclared (first use in this function)
     compute_embedding(&md_embed_sig, exc_embed_out, exc[1]);
                        ^
src/lpcnet.c:116:22: error: ‘dual_fc_2’ undeclared (first use in this function)
     compute_mdense2(&dual_fc_2, pdf_2, net->gru_b_state, exc_embed_out);
                      ^
src/lpcnet.c:87:11: warning: unused variable ‘pdf_2’ [-Wunused-variable]
     float pdf_2[DUAL_FC_2_OUT_SIZE];
           ^
src/lpcnet.c:86:11: warning: unused variable ‘pdf_1’ [-Wunused-variable]
     float pdf_1[DUAL_FC_1_OUT_SIZE];
           ^
Makefile:642: recipe for target 'src/lpcnet.lo' failed
make[1]: *** [src/lpcnet.lo] Error 1
make[1]: Leaving directory '/media/mzq/SDB/working/BunchedLPCnet'
Makefile:443: recipe for target 'all' failed
make: *** [all] Error 2
`

how to fixed this!

**Comment by tts-nlp** [comment]
hi @BridgetteSong ! thank you for your guidance , the training is normal, do you training using S=4?

**Comment by BridgetteSong** [comment]
1. I have not tried for S>2, because when S=2, the quality decline is quite obvious, and the speed for S=4 improves less than S=2. For me, the first priority is to improve the quality. I think using higher bit ulaw can help much, egs **10bit** or **11bit**. Or replacing ulaw with the **distribution** is a better choice, egs **Gaussian** or **Mixture of Logistic**, But I failed to implement the distribution version.
2. If you want to speed up more, **multi-band** is a better choice.

**Comment by BridgetteSong** [comment]
@tts-nlp 
Have you implemented the **Mixture of Logistic distribution** of LPCNet? Maybe I need your help.
[https://github.com/Min-jae/icassp2020/issues/1#issuecomment-619655828](url)

**Comment by tts-nlp** [comment]
when use S=2 to training model, the quality is similar for origin lpcnet for me using bake datasets, 

I used to use Mixture of Logistic distribution to achieve it, but the effect is not good, so I give up，Maybe there are some problems with it
