### ISSUE TITLE
请问推理的实时率是多少？

### ISSUE THREAD

**Issue by zhangsanfeng86** [BridgetteSong/BunchedLPCnet#3]

**Comment by forwiat** [comment]
我的测试效果：
BunchedLPCNet：
time ./lpcnet_demo -decode compressed.bin output.pcm

real    0m2.268s
user    0m1.940s
sys     0m0.021s

原始LPCNet：
time ./lpcnet_demo -decode compressed.bin output.pcm

real    0m1.182s
user    0m0.965s
sys     0m0.025s

同样的特征和机型

**Comment by BridgetteSong** [comment]
> 我的测试效果： BunchedLPCNet： time ./lpcnet_demo -decode compressed.bin output.pcm
> 
> real 0m2.268s user 0m1.940s sys 0m0.021s
> 
> 原始LPCNet： time ./lpcnet_demo -decode compressed.bin output.pcm
> 
> real 0m1.182s user 0m0.965s sys 0m0.025s
> 
> 同样的特征和机型

1. your based-LPCNet is newer than my baseline, because many new accelerate tricks are added, so new version LPCNet is faster than this one.
2. I update new BunchedLPCNet based on a September's LPCNet，and it can still 1.5X faster.
4. according to my imprecise memory：
    1. this version LPCNet can be 7 real-time rate
    2. new LPCNet can be 7-8 real-time rate
    3. my new BunchedLPCNet can 11-12 real-time rate

**Comment by wizardk** [comment]
> > 我的测试效果： BunchedLPCNet： time ./lpcnet_demo -decode compressed.bin output.pcm
> > real 0m2.268s user 0m1.940s sys 0m0.021s
> > 原始LPCNet： time ./lpcnet_demo -decode compressed.bin output.pcm
> > real 0m1.182s user 0m0.965s sys 0m0.025s
> > 同样的特征和机型
> 
> 1. 请不要使用-decoode，我没有实现-decode的功能，除非你自己实现了，不然是无法合成音频的
> 2. 请直接使用-synthesis
> 3. 不知道你的原始LPCNet是哪一个版本，请参照我实现的那个版本
> 4. 目前LPCNet的作者提交的最新版新增了很多加速trick，速度已经好于我这个版本了
> 5. 我基于作者今年九月份的某一版本，实现了最新的BunchedLPCNet，速度依然可以提升50%左右
> 6. 根据我的不准确测试记忆：
>    
>    1. 我基于的LPCNet版本大概5倍左右实时率，我这一版大概7倍左右
>    2. 作者目前的最新版应该到7-8倍左右了(记不清了，可以自己测一下)，基于作者最新版LPCNet，最新的BunchedLPCNet可以达到12左右

Will you update the newest LPCNet into your repo?

**Comment by BridgetteSong** [comment]
LPCNet author often updates his version, My newest version is based on his September version. When I tried to update based on his newest version, there are some bugs in my implements. Now I don't have much time to fix these bugs.
